### ISSUE TITLE
python-ilorest-library doesn't support py35

### ISSUE THREAD

**Issue by hugonicodemos** [HewlettPackard/python-ilorest-library#1]
I use python-ilorest-library with a python package created by my team and its configured with tox py27 and py35. So, when running tox -epy27 everything goes fine, but with **tox -epy35** the follow error occurs. Is there a plan to python-ilorest-library supports py35 and fix that? 

```bash
E File "/root/ironic-oneviewd/.tox/py35/lib/python3.5/site-packages/redfish/rest/v1.py", line 643
E       except ValueError, excp:
E                        ^
E   SyntaxError: invalid syntax
```

**Comment by luboss** [comment]
I fixed this by cloning source from git and running makeandinstallzip.bat. However I came to encountered another compatibility issue:
`File "C:\Python34\lib\site-packages\redfish\rest\v1.py", line 493, in __init__
    self.__url = urlparse2.urlparse(base_url)
AttributeError: 'module' object has no attribute 'urlparse'`

**Comment by naresh117** [comment]
i am still getting this issue

 self.__url = urlparse2.urlparse(base_url)
  AttributeError: 'module' object has no attribute 'urlparse'

can anyone help me on this?

**Comment by luboss** [comment]
Hello naresh117,

use python 2.x if possible. Otherwise even if you solve this you will have
further issues I think.

Regards,
Lubos
